import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

import currentReferrers from '../../src/generated/referrers.js';

interface SourceProvider {
  domains?: string[];
}

type SourceData = Record<string, Record<string, SourceProvider>>;
type ReferrerEntry = { name: string; type: string };

interface Manifest {
  referrers: {
    activeUrl: string;
    sourceUrl: string;
    snapshotDate: string;
    retrievedAt: string;
    sha256: string;
  };
}

const root = path.resolve(import.meta.dirname, '../..');
const manifestPath = path.join(root, 'upstream/manifest.json');
const extrasPath = path.join(root, 'upstream/openpanel-extra-referrers.json');
const outputPath = path.join(root, 'src/generated/referrers.ts');
const useLatest = process.argv.includes('--latest');

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}

function isoDate(value: Date): string {
  return value.toISOString().slice(0, 10);
}

function dateStampedUrl(activeUrl: string, date: string): string {
  return activeUrl.replace('referers-5.3.json', `referers-${date.replaceAll('-', '')}.json`);
}

async function download(url: string): Promise<{ body: string; lastModified: string | null }> {
  const response = await fetch(url, { headers: { 'user-agent': 'request-insights-updater/1.0' } });
  if (!response.ok) throw new Error(`Unable to download ${url}: HTTP ${response.status}`);
  return { body: await response.text(), lastModified: response.headers.get('last-modified') };
}

function transform(
  source: SourceData,
  extras: Record<string, ReferrerEntry>,
): Record<string, ReferrerEntry> {
  const entries: Record<string, ReferrerEntry> = {};
  for (const [rawType, providers] of Object.entries(source)) {
    const type = rawType === 'chatbot' ? 'ai' : rawType;
    for (const [name, provider] of Object.entries(providers)) {
      for (const domain of provider.domains ?? []) {
        entries[domain.toLowerCase()] = { name, type };
      }
    }
  }
  return Object.fromEntries(
    Object.entries({ ...entries, ...extras }).sort(([left], [right]) => left.localeCompare(right)),
  );
}

function quote(value: string): string {
  return `'${value
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')}'`;
}

function serializeEntries(entries: Record<string, ReferrerEntry>): string {
  return Object.entries(entries)
    .flatMap(([domain, entry]) => [
      `  ${quote(domain)}: {`,
      `    name: ${quote(entry.name)},`,
      `    type: ${quote(entry.type)},`,
      '  },',
    ])
    .join('\n');
}

function createDiff(
  previous: Readonly<Record<string, ReferrerEntry>>,
  next: Record<string, ReferrerEntry>,
) {
  const added = Object.keys(next).filter((domain) => !previous[domain]);
  const removed = Object.keys(previous).filter((domain) => !next[domain]);
  const changed = Object.keys(next)
    .filter(
      (domain) =>
        previous[domain] &&
        (previous[domain].name !== next[domain]?.name ||
          previous[domain].type !== next[domain]?.type),
    )
    .map((domain) => ({ domain, before: previous[domain], after: next[domain] }));
  return { added, removed, changed };
}

async function main(): Promise<void> {
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as Manifest;
  const extras = JSON.parse(await readFile(extrasPath, 'utf8')) as Record<string, ReferrerEntry>;
  let sourceUrl = manifest.referrers.sourceUrl;
  let downloaded = await download(useLatest ? manifest.referrers.activeUrl : sourceUrl);
  let snapshotDate = manifest.referrers.snapshotDate;

  if (useLatest) {
    if (!downloaded.lastModified)
      throw new Error('The active referrer response has no Last-Modified header.');
    snapshotDate = isoDate(new Date(downloaded.lastModified));
    sourceUrl = dateStampedUrl(manifest.referrers.activeUrl, snapshotDate);
    const immutableSnapshot = await download(sourceUrl);
    if (sha256(immutableSnapshot.body) !== sha256(downloaded.body)) {
      throw new Error(
        'Active and date-stamped Snowplow snapshots differ; refusing a non-reproducible update.',
      );
    }
    downloaded = immutableSnapshot;
  }

  const digest = sha256(downloaded.body);
  if (!useLatest && digest !== manifest.referrers.sha256) {
    throw new Error(
      `Recorded referrer snapshot hash mismatch: expected ${manifest.referrers.sha256}, received ${digest}`,
    );
  }

  const source = JSON.parse(downloaded.body) as SourceData;
  const entries = transform(source, extras);
  const diff = createDiff(currentReferrers, entries);
  const generated = [
    '/* This file is generated by scripts/upstream/sync-referrers.ts. Do not edit directly. */',
    `/* Snowplow snapshot: ${snapshotDate}; SHA-256: ${digest}; chatbot is normalized to ai. */`,
    '',
    'const referrers: Readonly<Record<string, { readonly name: string; readonly type: string }>> = {',
    serializeEntries(entries),
    '};',
    '',
    'export default referrers;',
    '',
  ].join('\n');
  await writeFile(outputPath, generated, 'utf8');

  if (useLatest) {
    manifest.referrers.sourceUrl = sourceUrl;
    manifest.referrers.snapshotDate = snapshotDate;
    manifest.referrers.retrievedAt = isoDate(new Date());
    manifest.referrers.sha256 = digest;
    await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

    const reportDirectory = path.join(root, 'tmp/upstream');
    const reportPath = path.join(reportDirectory, `referrers-${snapshotDate}.json`);
    await mkdir(reportDirectory, { recursive: true });
    await writeFile(
      reportPath,
      `${JSON.stringify({ snapshotDate, sha256: digest, ...diff }, null, 2)}\n`,
      'utf8',
    );
    console.log(
      `Behavior report: ${diff.added.length} added, ${diff.removed.length} removed, ${diff.changed.length} reclassified (${reportPath}).`,
    );
  }

  console.log(
    `Generated ${Object.keys(entries).length} referrer domains from ${sourceUrl} (${digest}).`,
  );
}

await main();
